name: Issue Assignment Notification

on:
  issues:
    types: [assigned, unassigned]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord embed
        uses: Ilshidur/action-discord@master
        with:
          args: |
            {
              "embeds": [
                {
                  "title": "${{ github.event.action == 'assigned' && '📌 Nouvelle tâche assignée' || '🚫 Assignation annulée' }}",
                  "color": "${{ github.event.action == 'assigned' && 5763719 || 15548997 }}",
                  "fields": [
                    {
                      "name": "Utilisateur concerné",
                      "value": "${{ github.event.assignee.login }}"
                    },
                    {
                      "name": "Action par",
                      "value": "${{ github.actor }}"
                    },
                    {
                      "name": "Issue",
                      "value": "${{ github.event.issue.title }}"
                    },
                    {
                      "name": "Lien",
                      "value": "${{ github.event.issue.html_url }}"
                    }
                  ]
                }
              ]
            }
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_ISSUE }}